### ISSUE TITLE
"Extras & Help" Pop-up Immediately Closes Itself

### ISSUE THREAD

**Issue by JKelner** [jmattthew/HeirloomRottenTomatoes#4]
![xnh](https://user-images.githubusercontent.com/7425391/32993254-e567caee-cd1a-11e7-8da4-7d7554d1c391.png)

This link opens an informational popup about HRT, but the popup immediately closes without any indication as to why.

As far as I can tell this is affecting all movie pages, irrespective of being logged in / not logged in.

**Comment by jmattthew** [comment]
Thanks for alerting me!  I'm seeing this too.  I'll try to fix ASAP.

**Comment by jmattthew** [comment]
Fixed as of 3.0.8.  It can take up to an hour from now for the new version to finish publishing.  @JKelner, many thanks for your report!

https://github.com/jmattthew/HeirloomRottenTomatoes/commit/3ef65a762fd99e7e4182f38b766c80ad08abfb91
